// Import the Skills styles from Skills.css.
import "../Styles/Skills.css";
// Import the Marquee component from react-fast-marquee.
import Marquee from "react-fast-marquee";
// Export the Skills component.
export default function Skills() {
  return (
    // Define the Marquee component with the following props.
    <Marquee
      autoFill={false}
      play={true}
      pauseOnHover={true}
      direction="left"
      speed={130} // Adjust the speed of the marquee.
      gradient={false} // Turn off gradient if not needed.
    >
      {/* Define the skills-container div with the skill-icon class. */}
      <div className="skills-container">
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Axios-35495E?style=flat-square&logo=axios&logoColor=white"
          alt="Axios"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-OpenAI-00AFF0?style=flat-square&logo=openai&logoColor=white"
          alt="OpenAI"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-React-45b8d8?style=flat-square&logo=react&logoColor=white"
          alt="React"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Webpack-8DD6F9?style=flat-square&logo=webpack&logoColor=white"
          alt="Webpack"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Sequelize-399FDB?style=flat-square&logo=sequelize&logoColor=white"
          alt="Sequelize"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-PostgreSQL-46a2f1?style=flat-square&logo=postgresql&logoColor=white"
          alt="PostgreSQL"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-CSS-1572B6?style=flat-square&logo=css3&logoColor=white"
          alt="CSS"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-jQuery-0769AD?style=flat-square&logo=jquery&logoColor=white"
          alt="jQuery"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Regex-4285F4?style=flat-square&logo=regex&logoColor=white"
          alt="Regex"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Github_Actions-2088FF?style=flat-square&logo=github-actions&logoColor=white"
          alt="Github Actions"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-TypeScript-3178C6?style=flat-square&logo=typescript&logoColor=white"
          alt="TypeScript"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Vite-646CFF?style=flat-square&logo=vite&logoColor=white"
          alt="Vite"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Insomnia-5849BE?style=flat-square&logo=insomnia&logoColor=white"
          alt="Insomnia"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Apollo-311C87?style=flat-square&logo=apollo-graphql&logoColor=white"
          alt="Apollo"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Netlify-430098?style=flat-square&logo=netlify&logoColor=white"
          alt="Netlify"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-ESLint-8A2BE2?style=flat-square&logo=eslint&logoColor=white"
          alt="ESLint"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-JASS-8E44AD?style=flat-square&logo=sass&logoColor=white"
          alt="JASS"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Bootstrap-7952B3?style=flat-square&logo=bootstrap&logoColor=white"
          alt="Bootstrap"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Redux-764ABC?style=flat-square&logo=redux&logoColor=white"
          alt="Redux"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-GraphQL-E10098?style=flat-square&logo=graphql&logoColor=white"
          alt="GraphQL"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Styled_Components-db7092?style=flat-square&logo=styled-components&logoColor=white"
          alt="Styled Components"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Workbox-FF6B6B?style=flat-square&logo=google-chrome&logoColor=white"
          alt="Workbox"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-NextJs-ea2845?style=flat-square&logo=nextjs&logoColor=white"
          alt="NextJs"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Jest-C21325?style=flat-square&logo=jest&logoColor=white"
          alt="Jest"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-NPM-CB3837?style=flat-square&logo=npm&logoColor=white"
          alt="NPM"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Day.js-FF5733?style=flat-square&logo=javascript&logoColor=white"
          alt="Day.js"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Brave_Browser-FB542B?style=flat-square&logo=brave&logoColor=white"
          alt="Brave Browser"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Lighthouse-FF5722?style=flat-square&logo=lighthouse&logoColor=white"
          alt="Lighthouse"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Git_Hooks-F05032?style=flat-square&logo=git&logoColor=white"
          alt="Git Hooks"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Git-F05032?style=flat-square&logo=git&logoColor=white"
          alt="Git"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-HTML5-E34F26?style=flat-square&logo=html5&logoColor=white"
          alt="HTML5"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Handlebars-FF9800?style=flat-square&logo=handlebars&logoColor=white"
          alt="Handlebars"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-JavaScript-F7DF1E?style=flat-square&logo=javascript&logoColor=black"
          alt="JavaScript"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Prettier-F7B93E?style=flat-square&logo=prettier&logoColor=white"
          alt="Prettier"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Tailwind%20CSS-38B2AC?style=flat-square&logo=tailwind-css&logoColor=white"
          alt="Tailwind CSS"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Netlify-00C7B7?style=flat-square&logo=netlify&logoColor=white"
          alt="Netlify"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-MongoDB-13aa52?style=flat-square&logo=mongodb&logoColor=white"
          alt="MongoDB"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-MongoDB_Atlas-13aa52?style=flat-square&logo=mongodb&logoColor=white"
          alt="MongoDB Atlas"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Mongoose-47A248?style=flat-square&logo=mongodb&logoColor=white"
          alt="Mongoose"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Bash-4EAA25?style=flat-square&logo=gnu-bash&logoColor=white"
          alt="Bash"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Nodejs-43853d?style=flat-square&logo=Node.js&logoColor=white"
          alt="Nodejs"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Express-000000?style=flat-square&logo=express&logoColor=white"
          alt="Express"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-JWT-000000?style=flat-square&logo=json-web-tokens&logoColor=white"
          alt="JWT"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-JSON-000000?style=flat-square&logo=json&logoColor=white"
          alt="JSON"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-GitHub_Pages-181717?style=flat-square&logo=github&logoColor=white"
          alt="GitHub Pages"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Render-333333?style=flat-square&logo=render&logoColor=white"
          alt="Render"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-IndexedDB-4D4D4D?style=flat-square&logo=indexeddb&logoColor=white"
          alt="IndexedDB"
        />
        <img
          className="skill-icon"
          src="https://img.shields.io/badge/-Python-white?style=flat-square&logo=python&logoColor=306998"
          alt="Python"
        />
      </div>
    </Marquee>
  );
}
